### ISSUE TITLE
Python errors when attempting to transfer shape keys.

### ISSUE THREAD

**Issue by ocalhoun6** [MykytaPetrenko/ShapeKeyWrap#2]
Your addon is brilliant and exactly what I very desperately need. (I need to transfer about a dozen custom shape keys from one character to over 40 other characters with the exact same topology. It would take _forever_ doing it manually.)

As far as the interface, selecting objects, and selecting shape keys goes, it's all working perfectly. The 'from' and 'to' meshes are selected properly.

But, unfortunately, every time I try to actually execute the transfer, I'm getting this same python error:
![Screenshot_20231215_143548](https://github.com/MykytaPetrenko/ShapeKeyWrap/assets/26573303/320f98a6-eb7b-47b1-a907-b85f1c745e06)
The same error comes up whether I'm just transferring one at a time, a select few, or all of them at once, whether I'm using "transfer by the list" or not.

Using Blender 4.0.1 and Python 3.10.13
Here's my blender setup information (including python version):
[system-info.txt](https://github.com/MykytaPetrenko/ShapeKeyWrap/files/13690219/system-info.txt)

If there's a way to fix this, it would be massively appreciated!

**Comment by ocalhoun6** [comment]
@MykytaPetrenko  
Forgot to mention: tried this in versions 3.0 and 3.2, and I'm getting the same result in both.

**Comment by MykytaPetrenko** [comment]
Hi. I develop the addon on windows, and this issue appears to me only with blender 4.0. I have updated the addon to version 3.3 today and it works for me, but I am not sure about linux, so you may check it.

Also I am not sure that this add-on is a good way to address your problem, cause it is generally devoloped to **approximatelly** transfer shapes from different topology. If topology and vertex indices are the same I would rather just copied shape key deltas from one mesh to another with a script, it should not be too hard.
