### ISSUE TITLE
Python Errors In Blender 4.1 And 4.0 (solved)

### ISSUE THREAD

**Issue by borodante** [MykytaPetrenko/ShapeKeyWrap#3]
<img width="693" alt="image" src="https://github.com/MykytaPetrenko/ShapeKeyWrap/assets/88441262/ac4522eb-10d9-4995-8472-a376a7eb2438">

Trying to transfer, and these errors show up, no transfer happens. "surface defrom" modifier is left in the target object.
Loving the addon, it's essential to make custom meshes work with Metahumans in UE5, but I can't use it lately!

**Comment by MykytaPetrenko** [comment]
Hi. If you used previous versions, make sure they are completely removed. I cannot get the same behavior, so if it is not a conflict with previous version, I need to get more to get the same behavior.

**Comment by borodante** [comment]
Thank you! I deleted the addon, restarted Blender and installed the addon again to find it working right away! Only now did I see the new "Bind Noise" checkbox btw. Took quite a while to do the transfer (metahumans have like 100+ shape keys), but it worked! It seems like it bound the shape keys with drivers, even though I didn't press Bind Values

**Comment by MykytaPetrenko** [comment]
By default it creates drivers. It is possible to uncheck on the parameters popup in the bottom left corner, recently I realized then it is not a good approach I will do some changes to the interface. But anyway the drivers are not exported to unreal.

**Comment by MykytaPetrenko** [comment]
Closed
